import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="th"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="app-nav" aria-label="เมนูหลัก">
        <div className="app-nav-inner">
          <Link href="/">หน้าแรก</Link>
          <Link href="/issue">รายการปัญหา</Link>
          <Link href="/issue/new">แจ้งปัญหาใหม่</Link>
        </div>
      </nav>
        {children}
      </body>
    </html>
  );
}
